# Escolha a versão do Node.js
FROM node:18

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie o package.json e o package-lock.json (se disponível)
# COPY package*.json ./

# Instale as dependências do projeto
# RUN npm install

# Copie os arquivos restantes do projeto
# COPY . .

# Exponha a porta que o Vite usa
EXPOSE 5173

# Comando para rodar o projeto em modo de desenvolvimento
# CMD ["npm", "run", "dev"]
