# Fase de build
FROM node:18 AS build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Fase de produção
FROM nginx:stable

COPY --from=build-stage /app/dist /usr/share/nginx/html

# Substitua a configuração padrão do Nginx pela sua própria configuração
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
